version: '3'
services:
  metrix_web:
    image: docker.pkg.github.com/mattcroberts/metrix/metrix-web:${METRIX_TAG}
    ports:
      - '8888:80'
    restart: always
  metrix_api:
    image: docker.pkg.github.com/mattcroberts/metrix/metrix-api:${METRIX_TAG}
    restart: always
    environment:
      - TYPEORM_CONNECTION=postgres # This triggers the CLI to use env variables
      - TYPEORM_HOST=metrix_postgres
      - TYPEORM_DATABASE=${METRIX_POSTGRES_DB_NAME}
      - TYPEORM_USERNAME=${METRIX_POSTGRES_USERNAME}
      - TYPEORM_PASSWORD=${METRIX_POSTGRES_PASSWORD}
      - TYPEORM_SYNCHRONIZE=false
      - TYPEORM_ENTITIES=/home/nodejs/app/build/**/*.model.js
      - TYPEORM_MIGRATIONS=/home/nodejs/app/build/migration/*.js
      - JWT_SECRET=${METRIX_JWT_SECRET}
      - GOOGLE_CLIENT_ID=${METRIX_GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${METRIX_GOOGLE_CLIENT_SECRET}
      - UI_HOST=${METRIX_UI_HOST}
      - API_PATH=${METRIX_API_PATH}
      - REDIS_HOST=metrix_redis
      - GOOGLE_APPLICATION_CREDENTIALS=${METRIX_GOOGLE_APPLICATION_CREDENTIALS}
    depends_on:
      - metrix_postgres
      - metrix_redis
    ports:
      - '8889:4000'
  metrix_postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${METRIX_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${METRIX_POSTGRES_PASSWORD}
      POSTGRES_DB: ${METRIX_POSTGRES_DB_NAME}
    volumes:
      - metrix_postgres:/var/lib/postgresql/data
  metrix_redis:
    image: redis:6-alpine
    restart: always
volumes:
  metrix_postgres:
