version: '3'
services:
  pgadmin:
    image: dpage/pgadmin4:alpine
    environment:
      PGADMIN_DEFAULT_EMAIL: mattroberts.uk@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 9999:80
  postgres:
    image: postgres:12-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: metrix
      POSTGRES_PASSWORD: metrix
      POSTGRES_DB: metrix
      PG_TRUST_LOCALNET: 'true'
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:6-alpine
    restart: always
    ports:
      - 6379:6379
volumes:
  postgres:
