version: '3'
services:
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: mattroberts.uk@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 9999:80
  postgres:
    image: postgres
    restart: always
    # Uncomment the next two lines to connect to your your database from outside the Docker environment, e.g. using a database GUI like Postico
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: metrix
      POSTGRES_PASSWORD: metrix
      POSTGRES_DB: metrix
      PG_TRUST_LOCALNET: 'true'
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
