name: Build + Deploy

on:
  push:
    branches: [master]

jobs:
  build-web:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: docker.pkg.github.com
          username: $GITHUB_ACTOR
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag docker.pkg.github.com/mattcroberts/metrix/metrix-web:$(git rev-parse --short "$GITHUB_SHA")
        working-directory: ./packages/web
      - name: Push image to registry
        run: docker push docker.pkg.github.com/mattcroberts/metrix/metrix-web:$(git rev-parse --short "$GITHUB_SHA")

  build-api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: docker.pkg.github.com
          username: $GITHUB_ACTOR
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag docker.pkg.github.com/mattcroberts/metrix/metrix-api:$(git rev-parse --short "$GITHUB_SHA")
        working-directory: ./packages/api
      - name: Push image to registry
        run: docker push docker.pkg.github.com/mattcroberts/metrix/metrix-api:$(git rev-parse --short "$GITHUB_SHA")
    
  deploy:
    runs-on: ubuntu-latest
    needs: ['build-web', 'build-api']

    steps:
      - uses: actions/checkout@v2
      - name: Create env
        run: |
          cat > env.sh <<- EOM
            export METRIX_TAG=$(git rev-parse --short "$GITHUB_SHA")
          EOM
      - name: SCP Files
        uses: appleboy/scp-action@master
        with:
          host: "irix.dev"
          username: ${{ secrets.DO_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.DO_KEY }}
          source: "docker-compose.yml,env.sh"
          target: "metrix"

